version: 2

jobs:
  build:
    docker:
      - image: andelf/doc-build:0.1.7
    working_directory: /src/pingcap/docs-cn
    steps:
      - checkout

      - run:
          name: "Merge Makedown Files"
          command: python3 scripts/merge_by_toc.py

      - run:
          name: "Generate PDF"
          command: scripts/generate_pdf.sh

  deploy:
    docker:
      - image: andelf/doc-build:0.1.7
    working_directory: /src/pingcap/docs-cn
    steps:
      - run:
          name: "Publish PDF"
          command: python3 scripts/upload.py output.pdf tidb-manual-cn.pdf

workflows:
  version: 2
  default-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master